name: CI/CD

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'STAGING'
        options:
        - 'STAGING'
        - 'PROD'


jobs:
  docker_build_publish:
    environment: ${{ github.event.inputs.environment }}
    name: Build and Publish Docker Image to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment variables
      run: |
        if [ "${{ github.event.inputs.environment }}" == 'STAGING' ]; then
          echo ${{ github.event.inputs.environment }}
          export IMAGE=$STAGING_IMAGE
          export TAG=$STAGING_TAG
          export ENVIROMENT=$STAGING_ENVIROMENT
          export REPO_NAME=$STAGING_REPO_NAME
        elif [ "${{ github.event.inputs.environment }}" == 'PROD' ]; then
          echo ${{ github.event.inputs.environment }}
          export IMAGE=$PROD_IMAGE
          export TAG=$PROD_TAG
          export ENVIROMENT=$PROD_ENVIROMENT
          export REPO_NAME=$PROD_REPO_NAME
        fi
      shell: bash
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          context: .
          build-args: |
            IMAGE=$IMAGE
            TAG=$TAG
            ENVIROMENT=$ENVIROMENT

          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${REPO_NAME}:latest-${{ github.run_number }}