name: CI/CD

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'PROD'
        options:
        - 'STAGING'
        - 'PROD'


jobs:
  docker_build_publish:

    if: github.event_name == 'push'
    environment: STAGING
    name: Build and Publish Docker Image to Staging
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          context: .
          build-args: |
            IMAGE=${{ vars.STAGING_IMAGE }}
            TAG=${{ vars.STAGING_TAG }}
            ENVIROMENT=${{ vars.STAGING_ENVIROMENT }}

          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.STAGING_REPO_NAME}}:latest-${{ github.run_number }}


  docker_build_manual:

    if: github.event_name == 'workflow_dispatch'
    name: Build and Publish Docker Image Manual
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment variables
      run: |
        if [ "${{ github.event.inputs.environment }}" == 'PROD' ]; then
          export IMAGE=$PROD_IMAGE
          export TAG=$PROD_TAG
          export ENVIROMENT=$PROD_ENVIROMENT
          export REPO_NAME=$PROD_REPO_NAME
        else
          export IMAGE=$STAGING_IMAGE
          export TAG=$STAGING_TAG
          export ENVIROMENT=$STAGING_ENVIROMENT
          export REPO_NAME=$STAGING_REPO_NAME
        fi
      shell: bash
    
    - name: Paso Print
      run: |
        echo "Mi variable es $IMAGE"
        echo "Mi variable es $TAG"
        echo "Mi variable es $REPO_NAME"
        echo "Mi variable es $PROD_REPO_NAME"
        echo "Mi variable es ${{ vars.REPO_NAME }}"
        echo "Mi variable es ${{ env.REPO_NAME }}"
        echo "Mi variable es ${{ vars.PROD_REPO_NAME }}"
        echo "Mi variable es ${{ env.PROD_REPO_NAME }}"
        echo "Mi variable es ${{ vars.STAGING_REPO_NAME }}"
        echo "Mi variable es ${{ env.STAGING_REPO_NAME }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          context: .
          build-args: |
            IMAGE=$IMAGE
            TAG=$TAG
            ENVIROMENT=$ENVIROMENT

          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:latest-${{ github.run_number }}