name: CI/CD

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'PROD'
        options:
        - 'STAGING'
        - 'PROD'


jobs:
  docker_build:

    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master'
    name: Build and Publish Docker Image (${{ github.event.inputs.environment || 'STAGING' }})
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'STAGING' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
          context: .
          build-args: |
            IMAGE=${{ vars.IMAGE }}
            TAG=${{ vars.TAG }}
            ENVIROMENT=${{ vars.ENVIROMENT }}

          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.REPO_NAME}}:latest-${{ vars.NAME_VERSION }}

    - name: Deploying to Render.com
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        curl "$deploy_url"
